### ISSUE TITLE
Autocomplete UX Update

### ISSUE THREAD

**Issue by pkrawc** [rentalutions/elements#123]
## User is unaware of how to delete/edit an already completed address

There are two options here in my mind, one potentially more natural but a lot harder to implement.

1. The easier option would be to add a close/delete icon next to the completed address

![image](https://user-images.githubusercontent.com/7158581/95778360-984c6e80-0c8d-11eb-86d1-b4136886eeca.png)

2. The harder option would be to move the cursor when there is a completed address so that you see it blinking just after the blue box. This would mean offsetting the input area and or filling the input with blank characters to equal the length of the address.

![image](https://user-images.githubusercontent.com/7158581/95778664-34767580-0c8e-11eb-8236-76516bc9ff59.png)

## Missing city/state in the label on completed address

This might be an implementation issue. Two things here, the autocomplete should be defaulted to full addresses, if we're not seeing that then we'll want to fix that. I also believe we're setting the `defaultValue` whenever the user chooses an address, we probably won't want to do that.

## Autocomplete starts at 4 keystrokes when old autocomplete starts at 1.

This is an easy fix in the `useAutocomplete` hook.

```js
useEffect(() => {
    // Get autocomplete suggestions based on input. Limit calls to inputs over 3
    // characters so we're not trying to guess too early.
    if (input.length > 3) {
      const request = {
        input,
        types: ["address"],
        sessionToken: state.sessionToken,
      }

      autocompleteRef.current.getPlacePredictions(request, updateSuggestions)
    } else {
      dispatch({
        type: "UPDATE_SUGGESTIONS",
        payload: { suggestions: [], called: false },
      })
    }
  }, [input])
```

## Unabled to up/down arrows to navigate the suggestion list.

This is a library change. Currently, you can tab through the list but you cannot use the arrow keys to enter and or navigate. This will take a bit of a redesign of the current implementation which is below

```js
function handleKeyDown({ keyCode }) {
    if (selection) {
      setInput("")
      return clearSelection(onClear)
    }
    switch (keyCode) {
      // Tab Key
      case 9:
        listRef.current?.firstElementChild.focus()
        break
      default:
        break
    }
  }
```

It should change to be more in line with what happens in the select component.

```js
// Attached to the input component
function handleKeyDown({ key }) {
    if (key === "ArrowDown") listRef.current.firstChild.focus()
    if (key === "Tab") dispatch({ type: types.CLOSE_LIST })
  }

// Attached to the list item component
function handleKeyDown({ key, target }) {
    const itemEl = itemRef.current
    if (key === "ArrowDown" && itemEl.nextSibling) itemEl.nextSibling.focus()
    if (key === "ArrowUp" && itemEl.previousSibling)
      itemEl.previousSibling.focus()
    if (key === "Enter") selectValue({ target })
    if (key === "Escape") dispatch({ type: types.CLOSE_LIST })
  }
```

@antonzaloznyy  Let me know if there is more context needed to get started on this.

CC: @wade00

**Comment by wade00** [comment]
@pkrawc thanks a ton for opening this up and giving some suggestions. @antonzaloznyy this can be worked on when you're ready. The feedback that lead to this issue being created is in [this airtable](https://airtable.com/tblkoPjYfI9Xkcynn/viw6843tbMpwyfaM5?blocks=hide).

**Comment by antonzaloznyy** [comment]
@pkrawc Thank you for great examples. It helps a lot! 
@wade00 Ok sounds good for me
