### ISSUE TITLE
Need an easy way to add styles to the ConfirmationDialog top div wrapper (Scrim)

### ISSUE THREAD

**Issue by tpstar** [rentalutions/elements#163]
**Is your feature request related to a problem? Please describe.**
* Version: "@rent_avail/dialog": "0.1.23"
* Steps to reproduce

  - on /app/landlords/dashboard, trigger a ConfirmationDialog. 
  - the property or tenant search bar, which has { position: sticky; z-index: 1; }, overlay on top of the confirmation dialog.

![Screen Shot 2021-04-27 at 7 41 45 AM](https://user-images.githubusercontent.com/18016578/116307526-0e1cb100-a76c-11eb-988b-06cd6549d5e2.png)

**Describe the solution you'd like**

- the issue can be fixed if we can send props to `Scrim` and set its z-index to 1
- but, the props for `ConfirmationDialog` are passed down to `ConfirmationWrapper` and not to `Scrim`.
- add a props for `ConfirmationDialog`, which can be named `wrapperStyles` and used for styling `Scrim`
e.g.

<ConfirmationDialog wrapperStyles={{ zIndex: 1 }} />

**Comment by pkrawc** [comment]
So I think you're onto the right solution. I wonder though if the API we go with would be more flexible and robust if we just exported the scrim component and required the user to add it to their mark-up.

```jsx
function AvailPage() {
  return (
    <Scrim>
      <ConfirmationDialog open={open}>
        <DialogHeader title="Title text." />
      </ConfimationDialog>
    </Scrim>
  )
}
```

Not exactly sure how to share the open prop without needing to pass it to both.

**Comment by tpstar** [comment]
> So I think you're onto the right solution. I wonder though if the API we go with would be more flexible and robust if we just exported the scrim component and required the user to add it to their mark-up.
> 
> ```js
> function AvailPage() {
>   return (
>     <Scrim>
>       <ConfirmationDialog open={open}>
>         <DialogHeader title="Title text." />
>       </ConfimationDialog>
>     </Scrim>
>   )
> }
> ```
> 
> Not exactly sure how to share the open prop without needing to pass it to both.

@pkrawc Yeah that would work. Although that would require changing all other existing ConfirmationDialogs. And the name `Scrim` can be confusing to other and future developers as to what it does. I think Bootstrap calls it `Backdrop`.
