### ISSUE TITLE
React is not defined when using Select from @rent_avail/controls

### ISSUE THREAD

**Issue by gabeff** [rentalutions/elements#165]
## Prerequisites

* Version: 0.2.17

## Step to reproduce (actual behavior)

- Import Select from "@rent_avail/controls"
- Add to a React component/view
- Run the react app
- It breaks with the error message: `Uncaught ReferenceError: React is not defined`

### Expected behavior

Successfully render Select components from "@rent_avail/controls"

Seems like we are missing to import React on:
controls/src/controls-hooks.js
controls/src/select/select-input.js
controls/src/select/select-item.js
controls/src/select/select-list.js
controls/src/select/select-provider.js 

## Any message or error

`Uncaught ReferenceError: React is not defined`

**Comment by pkrawc** [comment]
I _think_ the fix for this is changing the build/watch command to the following.

```
microbundle --jsx 'React.createElement' --jsxImportSource react --globals react/jsx-runtime=jsx
```

Stolen from this issue: https://github.com/developit/microbundle/issues/763
