### ISSUE TITLE
Error messages covering other UI elements

### ISSUE THREAD

**Issue by jgrubard** [rentalutions/elements#80]
## Prerequisites

* Version: `v1.6.15`
* Are you running from source/master: master
* Are you using a released build: YES
* Operating system: `macOS Catalina 10.15.4`
* Bits: `64-bit`

## Step to reproduce (actual behavior)

@pkrawc i don't believe this is not a bug but I think it is worth bringing up. I think there had been some discussion around the new inputs and not wanting the errors to have control over other UI behavior e.g. disallowing errors from pushing other elements to make room for the message.

I'm seeing the following behavior, and it's' more of an issue with smaller inputs/longer error messages:

![Screen Shot 2020-04-18 at 9 04 12 AM](https://user-images.githubusercontent.com/29084739/79640095-4ea71f00-8155-11ea-8c7c-42f0fcf5070c.png)

![Screen Shot 2020-04-18 at 9 05 19 AM](https://user-images.githubusercontent.com/29084739/79640097-4ea71f00-8155-11ea-8c7d-05a1d3622fb5.png)

### Expected behavior

I don't have a solution but I don't think we should be covering other elements with our error messages unless it's an intentional behavior, like a tooltip, mini-modal, etc. The current behavior feels like a bug.

## Any message or error

N/A

## Resources

N/A

**Comment by pkrawc** [comment]
Yeah. I think there are a number of trade offs with each solution. The errors are absolutely positioned right now so you could add 4rem of margin bottom. On the bottom row of inputs to compensate.

We also could have the string concat if longer than the width of the input. But then we wouldn't see the whole message...


@wade00 what is your opinion on this?

**Comment by jgrubard** [comment]
@pkrawc what if we truncated the message like you mentioned, and could display the entire message when the user hovers over the shortened version?

**Comment by pkrawc** [comment]
That's a good idea. Are you thinking a tooltip (maybe with a light red background) or something less invasive?

@jgrubard

**Comment by jgrubard** [comment]
@pkrawc i think either could work -- i like the idea of something less invasive, a tooltip would definitely get the job done but I could see it adding a lot of noise to the inputs. If the truncation would be handled by component logic over css, we could also possibly only render this tooltip/error popup _if_ the error message has been cut off, to reduce noise.

**Comment by creaumond** [comment]
Commenting to track this issue. Seeing the same issue on MFA error response. Temp solution was to change col from 4 to 6, but once a solution is established here, we should change there as well. 

`mfa_verification/ConfirmPhone.js`

**Comment by pkrawc** [comment]
@creaumond @jgrubard @wade00 

`v1.7.1` is published and has the changes mentioned above. The error row now implements a `title` attribute that shows the full error on hover or focus (if on mobile) and the red text is cut off at the width of the input.

There is no inherit margin attached to the bottom of the input still so each implementation will be responsible for adding that.

If possible using `@rent_avail/input` is preferable for the added spacing props that are available.
