### ISSUE TITLE
@rent_avail/input package theme props is not passed

### ISSUE THREAD

**Issue by tpstar** [rentalutions/elements#99]
## Prerequisites

* Version: "@rent_avail/input": "^0.1.7"
* Are you using a released build: Yes

## Step to reproduce (actual behavior)

- yarn add @rent_avail/input

- `import Input from "@rent_avail/input"` in a React component

- in the jsx of the React component, use `Input`

- This component is not rendered, and the whole page is broken

### Expected behavior

- `Input` component is rendered

## Any message or error

- Error message: `Cannot read property 'ui_500' of undefined`

## Possible ways to resolve this issue

- theme props is not passed to the Input

- when theme props is provided to `InputWrapper` in the source code, the issue is resolved

- to fix this issue;
1. allow users to pass theme props, or
2. provide theme props in the source code

**Comment by pkrawc** [comment]
Color props are not accepted on the input currently. What's the use case that you need to override the color scheme for the input component?

**Comment by pkrawc** [comment]
Theme props are passed to the input. Only `space` and `layout` are allowed.

**Comment by pkrawc** [comment]
If you want a workaround you could do

```jsx
const CustomInput = styled(Input)`
  color: ${({theme}) => theme.colors.ui_500};
`
```

**Comment by tpstar** [comment]
@pkrawc Sorry, if my comment is not clearly stating the issue. I am not trying to pass color props. The Input component does not work and raises the error `Cannot read property 'ui_500' of undefined` if I import `Input` from "@rent_avail/input" in my component. I think the source code breaks in packages/input/src/index.js line 27, where it tries to read theme.colors and gets undefined.

**Comment by pkrawc** [comment]
Gotcha.

That would mean that it doesn't have access to the theme object. It needs access to work so this failure is expected.

You have to use this (and any) component below the `ThemeProvider`. Possibly something from a merge conflict or just that the theme provider isn't loaded into your leaf of the application?

Are you working on the landlord or tenant side?

**Comment by tpstar** [comment]
@pkrawc this is related to an error message truncated to ellipsis when the error message is long. I saw this issue has been already fixed in the current version of @rent_avail/input. So, I was going to import the most current version of @rent_avail/input to fix the issue. I am working on a long error message not shown fully in a phone number register input, which will be used in both landlord and tenant sides.

**Comment by pkrawc** [comment]
Sorry, now I'm really not understanding. The `cannot read property 'ui_500' of undefined` is related to the error string on the input when the error is long?

Can you post more detailed steps to reproduce this because I'm not able to.

Aside I am seeing that the error message isn't truncating as expected. I probably missed updating this package when updating the legacy package with that behavior.

[Here is my attempt at recreating your issue.](https://codesandbox.io/s/busy-cray-r5see?file=/src/index.js)

**Comment by tpstar** [comment]
@pkrawc Sorry for another confusing comment  
This issue is not related to the truncated error message. 

The truncated error message was observed in the current Input component from "@rent_avail/elements/text-input" v"1.9.5" used in the current `rentalutions` codebase. 

I found that "@rent_avail/input": "^0.1.7" already resolved this truncated error message issue and tried to implement the Input from "@rent_avail/input": "^0.1.7". 

When I used Input from "@rent_avail/input": "^0.1.7" inside rentalutions codebase, nothing gets rendered and got `cannot read property 'ui_500' of undefined` error message in browser console.

**Comment by pkrawc** [comment]
Gotcha. Then yeah the fix is still to just move the provider up the tree probably. Let's connect early next week to try and knock this out.

**Comment by pkrawc** [comment]
@tpstar Did we ever resolve this?

**Comment by tpstar** [comment]
@pkrawc No, we haven't. Please let me know if you need help or test a fix.

**Comment by pkrawc** [comment]
@tpstar Can you send me a link to where this is implemented and you're seeing the error?

**Comment by tpstar** [comment]
in `front_end/ui_components/FieldInput/ElementFieldInput/ElementFieldInput.js` in `rentalutions`,

replace 

`import Input from "@rent_avail/elements/text-input"`

with

`import Input from "@rent_avail/input"`

then, I get 
`Uncaught TypeError: Cannot read property 'ui_500' of undefined`

This is related to this Trello bug ticket, `https://trello.com/c/OtXbKCG3/559-2fa-error-messages-do-not-display-in-full-for-mobile-or-desktop-users`.

**Comment by pkrawc** [comment]
We were able to resolve this by adding a `ThemeProvider` to the public pack in the rentalutions repo.
